### ISSUE TITLE
Adding Resources for learning Git and GitHub for New Beginners

### ISSUE THREAD

**Issue by lostgirljourney** [sukritishah15/DS-Algo-Point#12]
## 🚀 Feature

Want to add resources for those who're new to OPEN SOURCE Contribution.
ALL CONTRIBUTORS are welcome to contribute.

A Resources.md file shall be created for this issue. 
ALL CONTRIBUTORS can add their set of resources in this file.
Thank you!
 
### Have you read the Contribution Guidelines?

Yes

## Pitch

Since Hacktoberfest is around the corner, wanna help who're extremely new to Git and GitHub environment.

**Comment by sukritishah15** [comment]
Sure! @lostgirljourney We can do this!
Create a Resources.md file. 
Do not put this inside any folder. Can be created directly in the project root folder.
Also, this issue is open for all to contribute.

Nice initiative @lostgirljourney !!!

Let us know if you require any help.

**Comment by lostgirljourney** [comment]
Thank you so much @sukritishah15 di!🤩

**Comment by sunilgknair051** [comment]
Hi!
Would love to help out as well.

**Comment by sukritishah15** [comment]
> Hi!
> Would love to help out as well.

Sure! Go ahead!
This issue is open for all to contribute. 👍

**Comment by sb2356-iiitr** [comment]
Ok so where do we add the resources?

**Comment by sukritishah15** [comment]
> Ok so where do we add the resources?

I've added a RESOURCES.md file
Add resources over there 👍

**Comment by sb2356-iiitr** [comment]
> > Ok so where do we add the resources?
> 
> I've added a RESOURCES.md file
> Add resources over there

Ok

**Comment by khushboogupta13** [comment]
Hello! I really want to contribute to this project! Can anyone assign me an issue so that I can start working?

**Comment by ayushi-1408** [comment]
Hey I would love to do this

**Comment by Manavi18** [comment]
Hello! I really want to contribute to this project! Can anyone please assign me an issue so that I can start working?

**Comment by lostgirljourney** [comment]
@Manavi18 start working, it's an open issue.
