### ISSUE TITLE
Implement Singly Linked List

### ISSUE THREAD

**Issue by tdchua** [sukritishah15/DS-Algo-Point#140]
## 🚀 Feature

An implementation of the Singly Linked List data structure with commands such as:
- reverse traversal
- node deletion
- node insertion
- normal traversal

### Have you read the Contribution Guidelines?

Yes

## Pitch

I will be doing this in Python with proper commenting.

**Comment by viragz158** [comment]
I would like to do this in Java. First-timer here.

**Comment by Pratik-Patil-p0212-m3108** [comment]
I would like to do this in python. Can you please assign this issue to me?

**Comment by mephi007** [comment]
I can do this in Java, Can you please assign this to me?

**Comment by ShovikGod** [comment]
I can do this in C.

**Comment by FinalGetsugaa** [comment]
I would love to contribute in C++. Please Assign the task.

**Comment by malhotraravi842** [comment]
I would love to implement this in C++, please assign me this.

**Comment by pranavbharadwaj007** [comment]
I would love to implement this in C++.

**Comment by lostgirljourney** [comment]
Refer to issue no.: #23 @tdchua
