### ISSUE TITLE
Create CONTRIBUTION_GUIDELINES.md

### ISSUE THREAD

**Issue by tatticoder** [sukritishah15/DS-Algo-Point#154]
### Have you read the Contribution Guidelines?

Yes

## Pitch

I understand that having guidelines in readme.md is convenient and beginner friendly But, having a separate contributing.md in root of directory will make this repository more modular and structured. Many projects use this structure and GitHub shows a link at top of page to this file to make it easily accessible. 
Moreover, This would make it easier for veteran developers easier to contribute to this project and prepare amateur developers to work on other projects and make them familiar with industry standards.

## Assignees
@tatticoder

**Comment by tatticoder** [comment]
I would like to work on it. Please assign it to me.

**Comment by sukritishah15** [comment]
> I would like to work on it. Please assign it to me.

Agreed.
We were looking for people to do it.
Go ahead!
Create a CONTRIBUTION_GUIDELINES.md file

Assigned

**Comment by hritik5102** [comment]
Hello @sukritishah15 , i would like to work on this issue

Following thing, I would like to add in this repo 

- [x] **_CODE_OF_CONDUCT.md_**
- [x] **_Design ReadME and adding badge_**
- [x] **_.gitignore_**
- [x] **_Contributing.md_**

Thank you
