### ISSUE TITLE
Implement a code to find nth term of an A.P.

### ISSUE THREAD

**Issue by sukritishah15** [sukritishah15/DS-Algo-Point#2]
## 🚀 Feature

Given the first two terms, a1 and a2, of an A.P. (Arithmetic Progression), and an integer n, find the value of nth term in the A.P.

For example - 

Input: 
a1 = 2
a2 = 3
n=4

Output:
5

Explanation:
The A.P. for this example would be - 2, 3, 4, 5, 6, 7, ...

### Have you read the Contribution Guidelines?

Yes

## Pitch

This is an extremely simple mathematical problem. A good beginner-friendly issue.

## Assignees

@vanisha23 - C
@niranjantuty - C-Plus-Plus
@mananchawla2005 - Java
@mananchawla2005 - Python

**Comment by mananchawla2005** [comment]
Hey, can you assign me this issue? Will implement in as many languages I can as a part of hacktober fest? @sukritishah15

**Comment by niranjantuty** [comment]
Can I work on this?

**Comment by sukritishah15** [comment]
> Hey, can you assign me this issue? Will implement in as many languages I can as a part of hacktober fest? @sukritishah15

Sure, I have assigned this issue to you as a part of Hacktoberfest. Implement it in C.

**Comment by sukritishah15** [comment]
> Can I work on this?

Sure, I am assigning this to you in  C++.

**Comment by mananchawla2005** [comment]
Can I work on this is Python and Java. I dont know C that much ?  @sukritishah15

**Comment by sukritishah15** [comment]
> Can I work on this is Python and Java. I dont know C that much ? @sukritishah15

Okay, I will assign it to you in Python and Java both.

**Comment by vanisha23** [comment]
Can I work on this in Java, Python and C.

**Comment by sukritishah15** [comment]
> Can I work on this in Java, Python and C.

Assigning this to you in C.

**Comment by Algure** [comment]
I'd like to contribute in java
