### ISSUE TITLE
Looking for Collaborators - To review and merge code

### ISSUE THREAD

**Issue by sukritishah15** [sukritishah15/DS-Algo-Point#201]
## 🚀 Feature

Looking for Collaborators - To review and merge code.

Please leave a comment below.

## PERKS
We will be providing a LinkedIn recommendation and endorsements(Open Source / Git / GitHub / Version Control / Coding / Programming Language / Team work).

**Comment by sunilgknair051** [comment]
Can help out with review and merge. But let me be one among others. (have a busy schedule to deal with)

**Comment by sukritishah15** [comment]
> Can help out with review and merge. But let me be one among others. (have a busy schedule to deal with)
> Please assign.
> Thanks!
> -Sunil

Sure @sunilgknair051

**Comment by mephi007** [comment]
Hey @sukritishah15 I can help with review and merge.

**Comment by lostgirljourney** [comment]
@sukritishah15 di I can help you! 😄

**Comment by sukritishah15** [comment]
@mephi007 and @lostgirljourney 
You both are welcome to collaborate 👍 
I'm sending you invites for collaborator.

**Comment by erodrago** [comment]
Hey @sukritishah15 here to help where possible

**Comment by sukritishah15** [comment]
Thank you @erodrago.
I'm sending you invite for collaborator.

**Comment by sunilgknair051** [comment]
So, I have been looking at a few codes and realized that some of them might have been plagiarised. To all the Collaborators on this project, please look at them carefully and maybe we need a sieve to check this copy-paste attitude. Suggestions and improvements are welcome.

**Comment by lostgirljourney** [comment]
@sunilgknair051 generally codes are similar and coded in similar style so kind of false positive happens. Thing is you need to refer the code from somewhere so use it as reference and about plagiarism since this is about learning so it depends on person to person whether are learning or just doing for the sake of Hacktoberfest! 🙃

**Comment by ExpressHermes** [comment]
@sukritishah15 I am interested to be a collaborator. I can review codes in C, C++ and Python.

**Comment by sukritishah15** [comment]
@sunilgknair051 and @lostgirljourney Thank you for putting your points forward.

**Comment by sukritishah15** [comment]
> @sukritishah15 I am interested to be a collaborator. I can review codes in C, C++ and Python.

Sure! I have sent you invite for collaborator.
Thank you!
