### ISSUE TITLE
I want to add Quick Sort using arrays

### ISSUE THREAD

**Issue by asthapattanaik** [sukritishah15/DS-Algo-Point#260]
## 🚀 Feature

Implementation of Quick Sort algorithm using arrays

### Have you read the Contribution Guidelines?

Yes

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by sukritishah15** [comment]
@asthapattanaik - 
We already have/had an issue and code for Quick Sort.
Also, one cannot create a PR, until and unless they are assigned an issue.
Please close your PR.
