### ISSUE TITLE
Implement a code to find nth term of a G.P. 

### ISSUE THREAD

**Issue by sukritishah15** [sukritishah15/DS-Algo-Point#3]
## 🚀 Feature

Given the first two terms, a1 and a2, of an G.P. (Geometric Progression), and an integer n, find the value of nth term in the G.P.

For example -

Input:
a1 = 1
a2 = 2
n=4

Output:
8

Explanation:
The G.P. for this example would be - 1, 2, 4, 8, 16, ...

### Have you read the Contribution Guidelines?

Yes

## Pitch

This is an extremely simple mathematical problem. A good beginner-friendly issue.

## Assignees

@banerjee-suchismita - C
@Pratap2018 - C++
@niranjantuty - Java
@mananchawla2005 - Python

**Comment by mananchawla2005** [comment]
Hey can you assign me this as well for python. @sukritishah15 . I am new in open source and would like to contribute as much as I can.

**Comment by sukritishah15** [comment]
> Hey can you assign me this as well for python. @sukritishah15 . I am new in open source and would like to contribute as much as I can.

Yes, I've assigned it to you in Python.

**Comment by banerjee-suchismita** [comment]
Hello can you assign this to me in C? Would like to contribute !

**Comment by sukritishah15** [comment]
> Hello can you assign this to me in C? Would like to contribute !

Hello, I've assigned this issue to you in C.

**Comment by niranjantuty** [comment]
I would like to contribute.  Can you assign this to me in Java?

**Comment by Pratap2018** [comment]
i want to work on this

**Comment by sukritishah15** [comment]
> i want to work on this

Assigned in C++

**Comment by sukritishah15** [comment]
> I would like to contribute. Can you assign this to me in Java?

Assigned in Java.

**Comment by Pratap2018** [comment]
> > i want to work on this
> 
> Assigned in C++

thank you i will PR on October 1

**Comment by vanisha23** [comment]
I would like to contribute. Can you assign this to me in Java or Python or C.

**Comment by sukritishah15** [comment]
> > > i want to work on this
> > 
> > 
> > Assigned in C++
> 
> thank you i will PR on October 1

Sure, no problem at all. All the best for Hacktoberfest!

**Comment by sukritishah15** [comment]
> I would like to contribute. Can you assign this to me in Java or Python or C.

This issue has been take for all 4 programming languages. So, I won't be able to assign this one,
I and my team will be adding a few more issues, today itself. Stay tuned!

**Comment by ayushi-1408** [comment]
Hey ! I can do it in C

**Comment by Pratik-Patil-p0212-m3108** [comment]
@sukritishah15 Hey can I do this code in python? Can you please assign it to me? Thanks.
