### ISSUE TITLE
Urge to update topic:'hacktoberfest' to this repo

### ISSUE THREAD

**Issue by keivalya** [sukritishah15/DS-Algo-Point#314]
According to new Hacktoberfest update from the link:

https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by mahimagoyalx** [comment]
@sukritishah15 Please add topic:hacktoberfest to the repository.

**Comment by sukritishah15** [comment]
@keivalya @mahimagoyalx - I've added the required things
Thank you!
