### ISSUE TITLE
BODMAS Evaluator

### ISSUE THREAD

**Issue by Algure** [sukritishah15/DS-Algo-Point#337]
## 🚀 

An algorithm to evaluate elaborate arithmetic equations while observing the rules of BODMAS and accounts for common mathematical syntax and operators.

### Have you read the Contribution Guidelines?

Yes

## Pitch

It can be used in all sorts of algorithms. Its like having a scientific calculator to compute any mathematical expression in your program so you just input evan a complex expression and it gives the output; e.g evaluating an expression by =>gunnercal("2+3(sin30+cos(35+5^2))") gives "5" as output.

## Assignees
@Algure - Java

**Comment by sukritishah15** [comment]
Could you please let us know the programming language you would implement this in @Algure ?

**Comment by Algure** [comment]
JAVA...

**Comment by Algure** [comment]
May I proceed with the PR?

**Comment by sukritishah15** [comment]
@Algure Go ahead.
Assigned in JAVA
