### ISSUE TITLE
User input option for nth_term_of_ap.java file 

### ISSUE THREAD

**Issue by Siddhant-sarkar** [sukritishah15/DS-Algo-Point#351]
## 🚀 Feature

This feature allows the user to write the first terms and second term and nth Term.
Such that nth term is printed out/

### Have you read the Contribution Guidelines?
Yes,
very Well
## Pitch

In the current version, the required parameters are hardcoded such that user cannot input parameters of their choice.

**Comment by sukritishah15** [comment]
Go ahead @Siddhant-sarkar 
You are assigned.
Make changes in the same file. 👍
