### ISSUE TITLE
Implement Stack

### ISSUE THREAD

**Issue by Ayushmaan2001** [sukritishah15/DS-Algo-Point#36]
## 🚀 Feature

I've seen that Stack is missing from the data structure

### Have you read the Contribution Guidelines?

yes

## Pitch

Stack is one of the simple data structure ,if you''ll open this issue , i'd like to implement it it in cpp

**Comment by sukritishah15** [comment]
@Ayushmaan2001 - We have Issue #23 
In this we have taken up the implementation of some common data structures.
BUT, DSA is vast.
You can open issues for other data structures or their applications in standard problems.

Please, feel free to raise ISSUES.
Also, let me know the programming lang. you would like to take up the issue in - 4 available(C,C++,Java,Python)

**Comment by Ayushmaan2001** [comment]
> @Ayushmaan2001 - We have Issue #23
> In this we have taken up the implementation of some common data structures.
> BUT, DSA is vast.
> You can open issues for other data structures or their applications in standard problems.
> 
> Please, feel free to raise ISSUES.
> Also, let me know the programming lang. you would like to take up the issue in - 4 available(C,C++,Java,Python)

So this means that i can't implement stack and try any another data structure??
i would like to take up the issue in c++ language

**Comment by sukritishah15** [comment]
You can create issues for different data structures / Algorithms.
Example - Matrix Chain Multiplication (DP), Linked List is palindrome or not, Number is palindrome or not etc.
There are so many things... Pick any DS/Algo. for which an issue has not been created so far and code is absent in the codebase.
Create an issue for any of these. 👍 

Stack is already claimed by other contributors.
They would be adding the code for the same in a day or two.

Looking forward to issues from your end.

**Comment by shaswatsingh19** [comment]
Can I do this in python

**Comment by sukritishah15** [comment]
I'm sorry we are not taking up this issue.
As we have an open issue for implementing stack already.
And it has been claimed in Python.

You can always create new issues.
Thank you!
