### ISSUE TITLE
Algorithms in python

### ISSUE THREAD

**Issue by shaswatsingh19** [sukritishah15/DS-Algo-Point#38]
## 🚀 Feature

All the Algorithms in python which is easy to understand and can help the beginner to learn algorithm in python 

### Have you read the Contribution Guidelines?

Yes

## Pitch

Most of us do competitive programming in c++ or java but most of the competitive programmer doesn't use python so just trying to make a change here because if a beginner try to read a c++ file of a competitive programmer like William lin or tourist they would have known about a lot of things but python been a full high level that is very much similar to English it's easy of beginner to learn it.

**Comment by sukritishah15** [comment]
@shaswatsingh19 This is a good initiative.
But our intention is to implement a particular DS/Algo in all 4 programming languages - C, C++, Java, Python simultaneously.

What we can do is, you create issues for a DS that is not present in the codebase and for which there is no open issue or PR as of now.

We will assign that particular issue to you in Python.
And other contributors can claim it for other 3 programming languages.

Let me know, if that works for you.
Looking forward to more issues from your end!

**Comment by shaswatsingh19** [comment]
Yeah looks great,I will do that

**Comment by sukritishah15** [comment]
Thank you @shaswatsingh19
