### ISSUE TITLE
Code can now be added in Scala

### ISSUE THREAD

**Issue by rishabhsudan** [sukritishah15/DS-Algo-Point#383]
## 🚀 Feature

Implementation of famous algorithms in Scala.

### Have you read the Contribution Guidelines?
Yes

## Pitch
It would be great if our project consist of algorithms implemented in one of the most popular language : **Scala**.

**Comment by sukritishah15** [comment]
@rishabhsudan - Okay, We can do that.
I'll add a folder for that in the codebase in 5 minutes.
You can create issues for Code in Scala.
