### ISSUE TITLE
Dutch_National__Flag Problem

### ISSUE THREAD

**Issue by kamalrt11** [sukritishah15/DS-Algo-Point#398]
## 🚀 Dutch National Flag Problem

Algorithm to sort an array of 0's,1's and 2's.(Sort Colors by assigning numbers to it)

### Have you read the Contribution Guidelines?

Yes

## Pitch

It uses no extra space for sorting like in Merge Sort and Array is sorted in only One Traversal. It is an in-place algorithm.

**Comment by ShreyonSinha** [comment]
Can I work in this issue ?

**Comment by ExpressHermes** [comment]
I would like to work on this in C++ and Python.

**Comment by disha4u** [comment]
I would like to work in python

**Comment by disha4u** [comment]
this is duplicate of #282

**Comment by disha4u** [comment]
please close this
