### ISSUE TITLE
Twin  Prime numbers

### ISSUE THREAD

**Issue by Scarlet-Coder** [sukritishah15/DS-Algo-Point#407]
## 🚀 Feature

A program which will print all twin prime numbers present in a given range

### Have you read the Contribution Guidelines?

yes

## Assignees
@Scarlet-Coder - Java
@Hitansh159 - C++
@AmrutaKoshe - Python
@masterrachit777 - C#
@ayushpattnaik - C
@sejalshri - JavaScript

**Comment by Scarlet-Coder** [comment]
please assign me this in java

**Comment by Hitansh159** [comment]
please assign me in c++

**Comment by AmrutaKoshe** [comment]
please assign me this in python

**Comment by sukritishah15** [comment]
@Scarlet-Coder - Java
@Hitansh159 - C++
@AmrutaKoshe - Python

Assigned.

**Comment by masterrachit777** [comment]
Assign me this in C#

**Comment by arnav-roy** [comment]
@masterrachit777 - C#
Assigned.

**Comment by arnav-roy** [comment]
Kindly assign me C.

**Comment by ayushpattnaik** [comment]
Kindly assign me C

**Comment by arnav-roy** [comment]
@ayushpattnaik - C
Assigned.

**Comment by sejalshri** [comment]
@sukritishah15  @arnav-roy  please assign me, for implementation in Javascript.

**Comment by arnav-roy** [comment]
@sejalshri - JavaScript 
Assigned.

**Comment by natedtcc** [comment]
Hi, can I do this in PHP please? Thank you :)
