### ISSUE TITLE
Merge Sort (Check labels to know which programming languages can this issue be taken in)

### ISSUE THREAD

**Issue by musaabshirgar1** [sukritishah15/DS-Algo-Point#445]
## 🚀 Feature

Adding Merge Sorting Algorithm in Kotlin Language.

### Have you read the Contribution Guidelines?

Yes

## Assignees
@musaabshirgar1 - Kotlin
@scshiv29-dev - JavaScript
@natedtcc - PHP

**Comment by musaabshirgar1** [comment]
@sukritishah15 assign this to me.

**Comment by sukritishah15** [comment]
@musaabshirgar1 - Kotlin assigned

**Comment by scshiv29-dev** [comment]
can i get assigned in java script @sukritishah15

**Comment by arnav-roy** [comment]
@scshiv29-dev - JavaScript assigned.

**Comment by natedtcc** [comment]
Hi, can I implement this in PHP please? Thanks!

**Comment by arnav-roy** [comment]
@natedtcc - PHP
Assigned.

**Comment by hritik5102** [comment]
Hello @musaabshirgar1 , I would like to contribute to this issue

- [x] Merge sort using GO 

Thank you :)

**Comment by piyushsharma220699** [comment]
I can contribute this in C++ :) Assign this to me

**Comment by musaabshirgar1** [comment]
@hritik5102 sorry but i just raised the issue and i am not the maintainer if the repository. Tag any of the maintainers of this repository and they'll assign this issue to you.

**Comment by musaabshirgar1** [comment]
@piyushsharma220699 already implemented in c++.

**Comment by ShrutiRawal** [comment]
Hello @sukritishah15 , please assign this to me for **implementation in Java**. I've read the contribution guidelines.

**Comment by ardika99** [comment]
please assign me this issue in C++. If it is possible :)
