### ISSUE TITLE
Add Insertion Sort 

### ISSUE THREAD

**Issue by masterrachit777** [sukritishah15/DS-Algo-Point#446]
## 🚀 Feature

To add the insertion sort algorithm along with number of comparisons and number of movements.

### Have you read the Contribution Guidelines?

Yes.

## Pitch

It must be implemented as it is as important sorting algorithm.

**Comment by masterrachit777** [comment]
I would like to work on it using C++. Assign me please

**Comment by Devansh2005** [comment]
Can I do this in Python ?

**Comment by aditik03** [comment]
@sukritishah15 see if this issue should be continued or not

**Comment by masterrachit777** [comment]
Plzz assign me this.

**Comment by lostgirljourney** [comment]
@aditik03 refer to this issue #13 
@sukritishah15 di pls tell whether to close it or not!
