### ISSUE TITLE
Longest Common Subsequence

### ISSUE THREAD

**Issue by musaabshirgar1** [sukritishah15/DS-Algo-Point#455]
## 🚀 Feature

Implementing Longest Common Subsequence using Dynamic Programming in Kotlin

### Have you read the Contribution Guidelines?

Yes

### Assignees
@musaabshirgar1 - Kotlin

**Comment by aditik03** [comment]
@musaabshirgar1 - Kotlin

**Comment by piyushsharma220699** [comment]
I can do this in C++ :)

**Comment by sukritishah15** [comment]
@piyushsharma220699 - Actually, we already have code for LCS in C++.
