### ISSUE TITLE
Diameter of Binary Tree 

### ISSUE THREAD

**Issue by musaabshirgar1** [sukritishah15/DS-Algo-Point#458]
## 🚀 Feature

Implementing the Algorithm to find the Diameter of a Binary Tree 

### Have you read the Contribution Guidelines?

Yes

### Assignees
@musaabshirgar1 - Kotlin
@Sudheer121 - C++
@0utplay  - Java
@arnav-roy - Python
@yashkansal - C
@DemonDaddy22 - JavaScript
@cr33dx - Golang

**Comment by aditik03** [comment]
@musaabshirgar1 - Kotlin(assigned)

**Comment by Sudheer121** [comment]
Assign me this, for C++.

**Comment by 0utplay** [comment]
Can you assign me to this in Java

**Comment by arnav-roy** [comment]
@Sudheer121 - C++
@0utplay - Java
Assigned.

**Comment by arnav-roy** [comment]
Kindly assign me python.

**Comment by yashkansal** [comment]
I would like to implement it in c .Plz , assign me.

**Comment by arnav-roy** [comment]
@yashkansal - C
@arnav-roy - Python
Assigned.

**Comment by DemonDaddy22** [comment]
Assign this to me in JS.

**Comment by arnav-roy** [comment]
@DemonDaddy22 - JavaScript
Assigned.

**Comment by cr33dx** [comment]
i'd like to implement it in golang.

**Comment by DemonDaddy22** [comment]
@sukritishah15 @arnav-roy kindly review and merge the PR #506.

**Comment by arnav-roy** [comment]
@cr33dx - Golang
Assigned.
