### ISSUE TITLE
To add the complete Trigonometric Calculator .

### ISSUE THREAD

**Issue by Siddhant-sarkar** [sukritishah15/DS-Algo-Point#471]
## 🚀 Feature

This is an interactive console application for find Various Trigonometric ratio of angles typed by the user and the inverse of ratio typed by user

### Have you read the Contribution Guidelines?

Yes

## Pitch

The complete trigonometric calculator can find the Sine, Cosine, Tangent, Cotangent, Secant, Cosecant of any angle types in Degrees or Radians. And further, they can find the inverse of any value type.

**Comment by ayushpattnaik** [comment]
Assign me this for c++

**Comment by sukritishah15** [comment]
@Siddhant-sarkar - Assigned.

**Comment by deepansha-singh** [comment]
can I be assigned this issue in c++ or python?

**Comment by hemraj4545** [comment]
@sukritishah15 I wish to do the same with GoLang. Can you assign it to me?

**Comment by sukritishah15** [comment]
We are not taking up this issue for now.
