### ISSUE TITLE
Word Break Problem, Multisource Dijkstra, Fast Breadth First Search.  (30 PR's acceptable)

### ISSUE THREAD

**Issue by Ankitcode99** [sukritishah15/DS-Algo-Point#479]
## 🚀 Feature

I want to contribute as much as Graphs and Dynamic Programming examples as I could using the C++ Language.

### Have you read the Contribution Guidelines?

Yes i have read the guidelines.

## Pitch

C++ is the most fundamental and the strongest language which any computer science graduate face once in his/her life. So learning how to implement such beautiful algorithms would surely benefit every enthusiastic individual

### Word Break Problem
@Ankitcode99 - C++

### Multisource Dijkstra Algorithm
@Ankitcode99 - C++

### Fast Breadth First Search
@Ankitcode99 - C++

**Comment by sukritishah15** [comment]
@Ankitcode99 - C++
Assigned all 3.
