### ISSUE TITLE
Interpolation Search in JAVA and Improving Documentation

### ISSUE THREAD

**Issue by aditya-gite-04** [sukritishah15/DS-Algo-Point#519]
## 🚀 Feature

Given a sorted array of n uniformly distributed values arr[], write a function to search for a particular element x in the array

### Have you read the Contribution Guidelines?

Yes

## Pitch

This is already not present in the Java sub-repo so i would be contributing towards it and apart from that I would Surely Make the Documentation look more presentable and clean.

**Comment by aditya-gite-04** [comment]
Can I please work on this

**Comment by wallacecosta** [comment]
Hi @aditya-gite-04 , but unfortunately the interpolation search algorithm is already in progress with PR # 311 which has not yet been merged by a conflict that is being resolved.  About the idea of ​​improving documentation, tell us more about it and if you are interested, change the description to just improve the documentation.  Have a great week and thanks for collaborating
