### ISSUE TITLE
Longest Path in a DAG-(DP on Trees), k'th parent of a node - (DP on Trees), Number of unique path between 2 nodes-(DP on Trees) [30 PR's to be linked]

### ISSUE THREAD

**Issue by Ankitcode99** [sukritishah15/DS-Algo-Point#569]
## 🚀 Feature

(Write down a clear and concise description of what the feature is.)

### Have you read the Contribution Guidelines?

Yes

## Pitch

DP on trees is cool concept moreover at times it helps in solving some tough interview problems at FAANG companies I want to contribute in C++

### Longest Path in a DAG-(DP on Trees)
@Ankitcode99 - C++

### k'th parent of a node - (DP on Trees)
@Ankitcode99 - C++

### Number of unique path between 2 nodes-(DP on Trees)
@Ankitcode99 - C++

**Comment by sukritishah15** [comment]
@Ankitcode99 - C++
Assigned
