### ISSUE TITLE
Fenwick Tree - (Space Optimised Range Sum Query)

### ISSUE THREAD

**Issue by Ankitcode99** [sukritishah15/DS-Algo-Point#592]
## 🚀 Feature

Make space optimized range sum queries in logarithmic time.

### Have you read the Contribution Guidelines?

Yes, I have read the guidelines

## Pitch

Fenwick Tree helps folks get a clear understanding of bit manipulation operations along with solving a ton of range query problems in an optimised way.

I want to contribute in C++.

## Assignees
@Ankitcode99 - C++

**Comment by sukritishah15** [comment]
@Ankitcode99 - C++
Assigned

**Comment by aalokchaudhary** [comment]
@sukritishah15 can you please assign me this issue.

**Comment by Ankitcode99** [comment]
> 
> 
> @Ankitcode99 - C++
> Assigned

@sukritishah15 thanks for assigning me this issue but I have successfully got 4 Pull Requests merged to hacktoberfest repos. So it would be kind of you if you can assign this issue to @aalokchaudhary

**Comment by sukritishah15** [comment]
@aalokchaudhary - C++
Assigned

**Comment by itslinotlie** [comment]
I can do the Java implementation
