### ISSUE TITLE
Implement Merge sort

### ISSUE THREAD

**Issue by shaswatsingh19** [sukritishah15/DS-Algo-Point#60]
## 🚀 Feature

merge sort implementation in python

### Have you read the Contribution Guidelines?

Yes

## Pitch

Merge sort is a divide and conquer type algorithm with a time complexity of O(nlogn) which is better than selection and insertion sort

**Comment by shaswatsingh19** [comment]
Hey @sukritishah15 , I would like to work on it on python

**Comment by SuyashGupte** [comment]
I can do this in python
