### ISSUE TITLE
Greedy implementation of coin change problem

### ISSUE THREAD

**Issue by ameycodes** [sukritishah15/DS-Algo-Point#601]
## 🚀 Feature

This is a greedy implementation of the coin change problem. Finding the minimum number of denominations required.

### Have you read the Contribution Guidelines?

Yes

## Pitch

Useful in competitive programming and understanding the greedy algorithm

**Comment by ameycodes** [comment]
I would like to work on its C++ implementation

**Comment by ExpressHermes** [comment]
Duplicate of #171

**Comment by ExpressHermes** [comment]
Duplicate of #171
