### ISSUE TITLE
Rotate Linked List Clockwise

### ISSUE THREAD

**Issue by krishrahul98** [sukritishah15/DS-Algo-Point#602]
##  Rotate a Linked list

In this algorithm, we can rotate linked list clockwise(right) by given K value.
Language: C++

### Have you read the Contribution Guidelines?

Yes

## Pitch
Useful in common day to day programming.

**Comment by sukritishah15** [comment]
@krishrahul98 - C++
Assigned.

**Comment by chrk2205** [comment]
can i code it in C or Java
