### ISSUE TITLE
N-Queen Problem

### ISSUE THREAD

**Issue by IshaanSinghal1** [sukritishah15/DS-Algo-Point#611]
## 🚀 Feature

This problem is based on the concept of recursion and we can find number of ways to place N queens on N*N board.
I would like to use Java.

### Have you read the Contribution Guidelines?

Yes

## Pitch

Recursion is one of the most important part of DS and this is one of the classical problem of recursion.

**Comment by IshaanSinghal1** [comment]
Assign this to me- JAVA

**Comment by sukritishah15** [comment]
@IshaanSinghal1 - We already had this issue.
Feel free to open new issues.
Thank you!
