### ISSUE TITLE
Implement Binary Search 

### ISSUE THREAD

**Issue by jhoserpacheco** [sukritishah15/DS-Algo-Point#63]
## 🚀 Feature

Implement Binary Search

### Have you read the Contribution Guidelines?

Yes

## Pitch

It will help us to find elements in the arrays. Standard searching technique.

## Assignees

@jhoserpacheco - Java
@mcaupybugs - C++
@shaswatsingh19 - Python
@Pranav1642 - C
@pheeel  - JS
@LaxmiNyamagoud - PHP 
@AndreaBiondaro  - GO

**Comment by mcaupybugs** [comment]
Would like to implement the same in CPP. Please assign it to me.

**Comment by shaswatsingh19** [comment]
I can work with python

**Comment by Pranav1642** [comment]
I would work on c program of this issue

**Comment by ShovikGod** [comment]
Can I solve this issue in C??

**Comment by sukritishah15** [comment]
@jhoserpacheco - Java
@mcaupybugs - C++
@shaswatsingh19 - Python
@Pranav1642 - C
Assigned

Do remember -

1. Create a new PR. Create a new branch. Mention the issue # in your PR.
2. Add Sample I/P, O/P, Time and Space complexity in a single MULTILINE COMMENT.
DO NOT VIOLATE ANY OF THESE. Else, I will have to close the PR.

**Comment by GhostUser** [comment]
I will implement binary search in golang.

**Comment by GhostUser** [comment]
can you pls assign?

**Comment by TheOldTravellerNetwork** [comment]
Would like to add the recursive approach of Binary Search as well in C++

**Comment by pheeel** [comment]
I'd like to implement this in JS.

**Comment by niranjantuty** [comment]
@TheOldTravellerNetwork  Cannot assign this issue to you in C++ as it is already done.  You can choose C# / Go / PHP to work on this issue or feel free to work on other issues.

**Comment by LaxmiNyamagoud** [comment]
please assign this issue to me for php

**Comment by AndreaBiondaro** [comment]
Hi, can i do this in go?

**Comment by niranjantuty** [comment]
@LaxmiNyamagoud - PHP 
@AndreaBiondaro  - GO
Assigned!

**Comment by LaxmiNyamagoud** [comment]
> @LaxmiNyamagoud - PHP
> @AndreaBiondaro - GO
> Assigned!

I have completed please check it

**Comment by shashan27** [comment]
hi...
Could u assign this program?
I can deliver this in C or java.
