### ISSUE TITLE
UPDATE FOR ALL MAINTAINERS

### ISSUE THREAD

**Issue by sunilgknair051** [sukritishah15/DS-Algo-Point#649]
## UPDATE FOR ALL MAINTAINERS
Please go through the below thread of comments and do the needful. 
Thank you @sunilgknair051 for bringing this to the fore.
Thank you to all the maintainers as well !

Signed off - @sukritishah15 
---------------------------------------------------------------------------------

<br/><br/>

Working through some of the PRs I realized many of them aren't reading the contributing.md. 
And I think it is high time to invalidate PRs that have no questions answered and are spamming the repo. 

In lieu of this, I am suggesting that each PR from the collaborator's perspective should be assigned an additional reviewer.

So, assign a person when you are on a PR and if need be more on a single PR to double-check.

And please no favoritism, I observed a few of them mention a single person (collaborator) to merge.  Add a reviewer and merge only when both the reviewers are ok with the decision.

Thanks!
Thoughts @sukritishah15

**Comment by sukritishah15** [comment]
I totally understand your concern @sunilgknair051 
In fact, this is a very nice suggestion. I would love to have this in place.

But, we can do this, with a slight modification - If the PR is good to go and has no scope of improvement, then merge it directly. If you(any collaborator) , however feel that it requires a second review or you find the PR okayish, can be improved kind, then you can ask a second reviewer to review it.
I will explain the reasons for the above suggested modification -
1. Waiting for 2 reviews for a good PR doesn't make sense in case of a good PR.
2. It would increase our PR's in queue. Relatively new PR's or old PR's would suffer on this account.
3. Also, during hacktoberfest the in flow of PR's is relatively high, so we can implement the 2 review strategy in any other month, but October. So, I suggested this modification.

Also, a very personal account, I had come across a PR approved by 3 collaborators, but it was unmerged. So, I merged it.
Later, when I added the "hacktoberfest-acepted" label, I realized the PR had a lot of mistakes and all previous maintainers had approved it, given the fact that it was approved once. 

So, what do you say @sunilgknair051 ?
If it is okay, shall we go with the modified approach - which will save us time and effort and improvise quality of contributions?

Works for all collaborators cum maintainers?
All viewpoints or perceptions or thoughts are welcome.


Thank you!

**Comment by sukritishah15** [comment]
Also, @sunilgknair051 if you still feel that the modified approach is not okay and you would like to re-emphasize the importance of 2 reviewers for every PR, it is totally fine and understandable. You can put that up. Because, I personally, am a strong believer of what you said. It is just that, I feel it would increase our time being spent per PR, unnecessarily in case of Good PR's.

**Comment by sunilgknair051** [comment]
@sukritishah15 , thanks for the feedback. I feel the modified approach should work.
