### ISSUE TITLE
Binary Exponentiation

### ISSUE THREAD

**Issue by ayushab06** [sukritishah15/DS-Algo-Point#660]
## 🚀 Feature

Binary exponentiation is a trick which allows to calculate an using only O(logn) multiplications 

### Have you read the Contribution Guidelines?

yes

## Pitch

Binary exponentiation (also known as exponentiation by squaring) is a trick which allows to calculate an using only O(logn) multiplications (instead of O(n) multiplications required by the naive approach).

## Assignees
@ayushab06 - Java
@otacon94 - Python

**Comment by ayushab06** [comment]
assign it to me-java

**Comment by otacon94** [comment]
Can i do this in python?

**Comment by sukritishah15** [comment]
@otacon94 - Python
Assigned

**Comment by Hrishikesh-Thakkar** [comment]
Can I do this in C-Plus-Plus?

**Comment by chhipanikhil9** [comment]
i can do in java

**Comment by ayushab06** [comment]
hey,the merge conflict has been resolved.
