### ISSUE TITLE
BFS.c

### ISSUE THREAD

**Issue by PUSHPASINGH00** [sukritishah15/DS-Algo-Point#686]
## 🚀 Feature

(Write down a clear and concise description of what the feature is.)

### Have you read the Contribution Guidelines?

(Write your answer here.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

**Comment by PUSHPASINGH00** [comment]
#685

**Comment by sahilparwani** [comment]
Can you assign me this issue?

**Comment by niranjantuty** [comment]
@PUSHPASINGH00  Please answer the questions while creating an issue. 

> ## 🚀 Feature
> (Write down a clear and concise description of what the feature is.)
> 
> ### Have you read the Contribution Guidelines?
> (Write your answer here.)
> 
> ## Pitch
> (Please explain why this feature should be implemented and how it would be used.)
