### ISSUE TITLE
Binary Indexed Tree

### ISSUE THREAD

**Issue by SunRub** [sukritishah15/DS-Algo-Point#766]
## 🚀 Feature

A 2D binary indexed tree, also known as a 2D Fenwick tree, is a data structure which can update elements and calculate sum queries efficiently.

### Have you read the Contribution Guidelines?

Yes.

## Pitch

The 2D binary indexed tree is useful for (competitive) programming. Programming languages used for it will include C++ and Java.

**Comment by itslinotlie** [comment]
@SunRub see Issue #592 and #714

**Comment by itslinotlie** [comment]
Closing this because of repeated issue
