### ISSUE TITLE
I want a program to check if a binary  tree is a BST or not 

### ISSUE THREAD

**Issue by Lucifer1149** [sukritishah15/DS-Algo-Point#829]

**Comment by TusharKalyankar** [comment]
Yes @Lucifer1149, I would like to do it in JAVA.

**Comment by TusharKalyankar** [comment]
@Lucifer1149, I would like to do it using JAVA

**Comment by sukritishah15** [comment]
This issue is not in accordance with the format prepared (specifically for this repository) for creating an Issue. 
Closing this issue. Kindly open a new Issue, in the correct format.

Thanks!
